### ISSUE TITLE
Fix repository link in pyproject.toml

### ISSUE THREAD

**Issue by lauri-codes** [FAIRmat-NFDI/nomad-catalysis-plugin#26]
The repository link in `pyproject.toml` seems to point to your old repo (https://github.com/schumannj/nomad-catalysis). Maybe also check that everything else is up-to-date in that file :+1:

**Comment by schumannj** [comment]
Thanks @lauri-codes , I didnt realize. Thanks!
Regarding the nomad-lab version, because of the new Filter menu, I would now require nomad-lab version 1.3.11, right?

**Comment by lauri-codes** [comment]
Yes, 1.3.11 should have it.
